"""add workspace llm_config

Revision ID: 73ac718e2de0
Revises: 725dbb1ee1c2
Create Date: 2026-08-25 23:43:28.873267
"""
from alembic import op
import sqlalchemy as sa


revision = '73ac718e2de0'
down_revision = '725dbb1ee1c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # server_default backfills existing workspaces so the NOT NULL add
    # succeeds on Postgres tables that already have rows.
    op.add_column(
        'workspaces',
        sa.Column('llm_config', sa.JSON(), nullable=False, server_default='{}'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'llm_config')
    # ### end Alembic commands ###
