"""Shared rate-limit counters.

Moves rate limiting out of process memory. An in-memory limiter grants each
web instance the full allowance (N instances = N x the limit) and loses every
lockout on restart; this table makes the count global without adding Redis.

Original message: shared rate limit counters

Revision ID: ccd7a43f22f0
Revises: e5f6a7b8c9d0
Create Date: 2026-08-31 18:12:44.716980
"""
from alembic import op
import sqlalchemy as sa


revision = 'ccd7a43f22f0'
down_revision = 'e5f6a7b8c9d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_counters',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('bucket', sa.String(length=320), nullable=False),
    sa.Column('window_start', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket', 'window_start', name='uq_rate_window')
    )
    op.create_index('ix_rate_limit_window_start', 'rate_limit_counters', ['window_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rate_limit_window_start', table_name='rate_limit_counters')
    op.drop_table('rate_limit_counters')
    # ### end Alembic commands ###
